DROP TABLE OFERTACOMUN CASCADE CONSTRAINTS;
DROP TABLE OFERTAEXCLUSIVA CASCADE CONSTRAINTS;
DROP TABLE VIVIENDAUNIVERSITARIA CASCADE CONSTRAINTS;
DROP TABLE APARTAMENTO CASCADE CONSTRAINTS;
DROP TABLE EMPRESA CASCADE CONSTRAINTS;
DROP TABLE VECINO CASCADE CONSTRAINTS;
DROP TABLE VIVIENDA CASCADE CONSTRAINTS;
DROP TABLE HOSPEDAJE CASCADE CONSTRAINTS;
DROP TABLE ADMINVIVIENDA CASCADE CONSTRAINTS;
DROP TABLE PROPIETARIOMIEMBRO CASCADE CONSTRAINTS;
DROP TABLE CLIENTE CASCADE CONSTRAINTS;
DROP TABLE CLIENTEMIEMBRO CASCADE CONSTRAINTS;
DROP TABLE RESERVACOMUN CASCADE CONSTRAINTS;
DROP TABLE CONTRATO CASCADE CONSTRAINTS;
DROP SEQUENCE alohandes_sequence;

commit;
