SELECT capacidad
FROM OFERTACOMUN;

SELECT habitacioncompartida
FROM OFERTAEXCLUSIVA;

SELECT HABITACIONCOMPARTIDA
FROM VIVIENDAUNIVERSITARIA;

SELECT HABITACIONCOMPARTIDA
FROM APARTAMENTO;

SELECT CAPACIDAD
FROM VIVIENDA;

SELECT CAPACIDAD
FROM HOSPEDAJE;